# Generated by Django 6.0.2 on 2026-02-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrudeOilProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('company_name', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.FloatField(blank=True, help_text='Production in 000 metric tonnes', null=True)),
            ],
            options={
                'ordering': ['-year', 'month'],
                'indexes': [models.Index(fields=['company_name', 'year'], name='petroleum_c_company_705d94_idx')],
                'unique_together': {('month', 'year', 'company_name')},
            },
        ),
        migrations.CreateModel(
            name='PetroleumImportExportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_export', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=100)),
                ('monthly_data', models.JSONField(default=dict, help_text='Monthly volumes: {april: x, may: y, ...}')),
                ('total', models.FloatField(blank=True, help_text='Annual total in 000 metric tonnes', null=True)),
            ],
            options={
                'ordering': ['import_export', 'product'],
                'unique_together': {('import_export', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PetroleumProductProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('product', models.CharField(db_index=True, max_length=100)),
                ('quantity', models.FloatField(blank=True, help_text='Production in 000 metric tonnes', null=True)),
            ],
            options={
                'ordering': ['-year', 'month'],
                'indexes': [models.Index(fields=['product', 'year'], name='petroleum_p_product_943184_idx')],
                'unique_together': {('month', 'year', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PetroleumTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(db_index=True, help_text='Month as number (1-12)')),
                ('year', models.IntegerField(db_index=True)),
                ('product', models.CharField(db_index=True, max_length=200)),
                ('trade_type', models.CharField(choices=[('Import', 'Import'), ('Export', 'Export')], db_index=True, max_length=10)),
                ('quantity', models.FloatField(blank=True, help_text='Quantity in 000 metric tonnes', null=True)),
                ('value_inr_crore', models.FloatField(blank=True, help_text='Value in Rupees (Crore)', null=True)),
                ('value_usd_million', models.FloatField(blank=True, help_text='Value in US Dollars (Million)', null=True)),
                ('date_updated', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['product', 'trade_type', 'year'], name='petroleum_p_product_a65876_idx'), models.Index(fields=['trade_type', 'year'], name='petroleum_p_trade_t_9ec3a1_idx')],
                'unique_together': {('month', 'year', 'product', 'trade_type')},
            },
        ),
        migrations.CreateModel(
            name='RefineryProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(db_index=True, max_length=20)),
                ('year', models.IntegerField(db_index=True)),
                ('refinery_name', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.FloatField(blank=True, help_text='Crude oil processed in 000 metric tonnes', null=True)),
            ],
            options={
                'ordering': ['-year', 'month'],
                'indexes': [models.Index(fields=['refinery_name', 'year'], name='petroleum_r_refiner_683e1d_idx')],
                'unique_together': {('month', 'year', 'refinery_name')},
            },
        ),
    ]
