# Generated by Django 6.0.2 on 2026-02-11 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('group', models.CharField(blank=True, max_length=100)),
                ('typical_season', models.CharField(blank=True, choices=[('Kharif', 'Kharif'), ('Rabi', 'Rabi'), ('Whole Year', 'Whole Year'), ('Summer', 'Summer'), ('Winter', 'Winter'), ('Autumn', 'Autumn')], max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DemandSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_group', models.CharField(max_length=100, unique=True)),
                ('projected_demand_2016_17', models.FloatField(blank=True, help_text='Million tonnes', null=True)),
                ('projected_demand_2020_21', models.FloatField(blank=True, help_text='Million tonnes', null=True)),
                ('projected_supply_2016_17_low', models.FloatField(blank=True, help_text='Million tonnes (low)', null=True)),
                ('projected_supply_2016_17_high', models.FloatField(blank=True, help_text='Million tonnes (high)', null=True)),
                ('actual_production_2006_07', models.FloatField(blank=True, help_text='Million tonnes', null=True)),
                ('actual_production_2011_12', models.FloatField(blank=True, help_text='Million tonnes', null=True)),
            ],
            options={
                'verbose_name_plural': 'Demand & Supply',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('capital_city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity_tonnes', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri.crop')),
                ('source_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri.district')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to=settings.AUTH_USER_MODEL)),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_queries', to='agri.state')),
            ],
            options={
                'verbose_name_plural': 'Procurement Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_supply_tonnes', models.FloatField()),
                ('price_per_tonne', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transportation_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('distance_km', models.FloatField()),
                ('estimated_delivery_days', models.FloatField()),
                ('carbon_footprint_kg', models.FloatField(help_text='CO2 equivalent in kg')),
                ('ranking_category', models.CharField(blank=True, choices=[('best_cost', 'Best Cost'), ('fastest', 'Fastest Delivery'), ('lowest_carbon', 'Lowest Carbon')], max_length=20)),
                ('ranking_score', models.FloatField(blank=True, null=True)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='agri.procurementquery')),
                ('supplier_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agri.district')),
                ('supplier_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agri.state')),
            ],
            options={
                'ordering': ['total_cost'],
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='agri.state'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agri.district')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agri.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('name', 'state')},
        ),
        migrations.CreateModel(
            name='DistanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('duration_hours', models.FloatField()),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('destination_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='agri.district')),
                ('origin_district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='agri.district')),
                ('destination_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='agri.state')),
                ('origin_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='agri.state')),
            ],
            options={
                'unique_together': {('origin_state', 'origin_district', 'destination_state', 'destination_district')},
            },
        ),
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_year', models.IntegerField(db_index=True)),
                ('season', models.CharField(max_length=30)),
                ('area', models.FloatField(blank=True, help_text='Area in hectares', null=True)),
                ('production', models.FloatField(blank=True, help_text='Production in tonnes', null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='agri.crop')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='agri.district')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='agri.state')),
            ],
            options={
                'indexes': [models.Index(fields=['crop', 'crop_year'], name='agri_croppr_crop_id_e91b76_idx'), models.Index(fields=['state', 'crop'], name='agri_croppr_state_i_83feeb_idx'), models.Index(fields=['state', 'crop', 'crop_year'], name='agri_croppr_state_i_02b409_idx')],
                'unique_together': {('state', 'district', 'crop', 'crop_year', 'season')},
            },
        ),
        migrations.CreateModel(
            name='CropPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_tonne', models.DecimalField(decimal_places=2, help_text='INR per tonne', max_digits=12)),
                ('year', models.IntegerField()),
                ('source', models.CharField(default='MSP', help_text='MSP, Market, Estimated', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='agri.crop')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_prices', to='agri.state')),
            ],
            options={
                'indexes': [models.Index(fields=['crop', 'state'], name='agri_croppr_crop_id_0dc06f_idx')],
                'unique_together': {('crop', 'state', 'year')},
            },
        ),
    ]
