# Generated by Django 6.0.2 on 2026-02-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementquery',
            name='transport_mode',
            field=models.CharField(choices=[('road', 'Road Only'), ('rail', 'Rail Only'), ('both', 'Both Road & Rail')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='procurementresult',
            name='transport_mode',
            field=models.CharField(choices=[('road', 'Road'), ('rail', 'Rail')], default='road', max_length=10),
        ),
        migrations.CreateModel(
            name='RailwayFreightRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_class', models.CharField(choices=[('130A', 'Train Load - Food Grains (130A)'), ('130B', 'Wagon Load - Food Grains (130B)'), ('LR3', 'Train Load - Spices/Sugar (LR3)'), ('LR3W', 'Wagon Load - Spices/Sugar (LR3W)')], max_length=10)),
                ('min_distance_km', models.IntegerField()),
                ('max_distance_km', models.IntegerField()),
                ('rate_per_tonne', models.DecimalField(decimal_places=2, help_text='INR per tonne', max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Railway Freight Rates',
                'ordering': ['rate_class', 'min_distance_km'],
                'unique_together': {('rate_class', 'min_distance_km', 'max_distance_km')},
            },
        ),
    ]
